# This file was generated by GoReleaser. DO NOT EDIT.
class Apizza < Formula
  desc "Command line tool for ordering Dominos pizza."
  homepage "https://github.com/harrybrwn/apizza"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/harrybrwn/apizza/releases/download/v0.0.3/apizza_0.0.3_MacOS_64-bit.tar.gz"
    sha256 "3695d5829b281d0666cd891c655051be4344f7201c9125609d43b3530dacac4b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/harrybrwn/apizza/releases/download/v0.0.3/apizza_0.0.3_Linux_64-bit.tar.gz"
      sha256 "5bdf953005b9da6856d6dcc64fd7719af31ba7a57091f0f91903c1290e406157"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harrybrwn/apizza/releases/download/v0.0.3/apizza_0.0.3_Linux_arm64.tar.gz"
        sha256 "d37e69f6548fc50abcf4723fec43276ddc4a3db9445f93a7dd3003199e77f9f6"
      else
      end
    end
  end

  def install
    bin.install "apizza"
  end

  test do
    system "#{bin}/apizza --version"
  end
end
