# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edu < Formula
  desc "Command line tool for managing school stuff"
  homepage "https://github.com/harrybrwn/edu"
  version "0.0.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/harrybrwn/edu/releases/download/v0.0.4/edu_0.0.4_MacOS_64-bit.tar.gz"
    sha256 "57050c8d2e1e163f6a1ab8f8e069d150935a6c23d694699c41777354ae215440"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/harrybrwn/edu/releases/download/v0.0.4/edu_0.0.4_Linux_64-bit.tar.gz"
    sha256 "0b1e87d37524039688c6c67a9ab716d763122a3e671895bd66cb31573dd76f69"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/harrybrwn/edu/releases/download/v0.0.4/edu_0.0.4_Linux_arm64.tar.gz"
    sha256 "ed9061c9616da5adb399bc726dcffa4cebcff6b2cf36547a10703261fe17a834"
  end

  def install
    bin.install "edu"
  end

  test do
    system "#{bin}/edu --version"
  end
end
