# This file was generated by GoReleaser. DO NOT EDIT.
class Edu < Formula
  desc "Command line tool for managing school stuff"
  homepage "https://github.com/harrybrwn/edu"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/harrybrwn/edu/releases/download/v0.0.3/edu_0.0.3_MacOS_64-bit.tar.gz"
    sha256 "fbf717239928669c11409687d1ceb29cc5660707f1afd216a43343b0d8ddf141"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/harrybrwn/edu/releases/download/v0.0.3/edu_0.0.3_Linux_64-bit.tar.gz"
      sha256 "29a00f0fd4c9fd6c9b1023a1ffd923e1884f5992266d09ac05ef5f0d64b3f338"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harrybrwn/edu/releases/download/v0.0.3/edu_0.0.3_Linux_arm64.tar.gz"
        sha256 "c4debd532c32c91b282fb853ce1f70b72315927f74638d8e9e6fb0628bdde7d8"
      else
      end
    end
  end

  def install
    bin.install "edu"
  end

  test do
    system "#{bin}/edu --version"
  end
end
