# This file was generated by GoReleaser. DO NOT EDIT.
class Edu < Formula
  desc "Command line tool for managing school stuff"
  homepage "https://github.com/harrybrwn/edu"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/harrybrwn/edu/releases/download/v0.0.2/edu_0.0.2_MacOS_64-bit.tar.gz"
    sha256 "65ed1570eb899e38d20132cb5aa7656e313f99584afb1643ad0ffe0b4d9745ce"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/harrybrwn/edu/releases/download/v0.0.2/edu_0.0.2_Linux_64-bit.tar.gz"
      sha256 "17c4d16221239252135319cc27980e7bc72ba6cafd684eacb3ddc48993fcff0a"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harrybrwn/edu/releases/download/v0.0.2/edu_0.0.2_Linux_arm64.tar.gz"
        sha256 "652f00f7a82149019656191e6c9a6f8f03f3c9d871ad7b4cb983f831e7cf0c00"
      else
      end
    end
  end

  def install
    bin.install "edu"
  end

  test do
    system "#{bin}/edu --version"
  end
end
