# This file was generated by GoReleaser. DO NOT EDIT.
class Yt < Formula
  desc "Command line YouTube video and audio downloader"
  homepage "https://github.com/harrybrwn/yt"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/harrybrwn/yt/releases/download/v0.1.0/yt_0.1.0_MacOS_x86_64.tar.gz"
    sha256 "56d9eeba445ad4fdfb6863f951f1af68cc81630ffaa055d5f0142d68b32eaba3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/harrybrwn/yt/releases/download/v0.1.0/yt_0.1.0_Linux_x86_64.tar.gz"
      sha256 "0f56fb3b2384a740e9017f48b2a14687e36be6c3aa627413a9a13863afcf25b1"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harrybrwn/yt/releases/download/v0.1.0/yt_0.1.0_Linux_arm64.tar.gz"
        sha256 "0f86206e49a2ced5da2972f1d9f26d1cc6aaf774d3c12e103e667a9aa2e091a8"
      else
      end
    end
  end

  def install
    bin.install "yt"
  end

  test do
    system "#{bin}/yt version"
  end
end
